// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/core/event/proto/v1/event.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Meta                 *Meta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a56999bb3a91d08, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Meta struct {
	EventId              string               `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string               `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId          string               `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string               `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a56999bb3a91d08, []int{1}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Meta) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Meta) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Meta) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Meta) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "oswee.core.event.v1.Event")
	proto.RegisterType((*Meta)(nil), "oswee.core.event.v1.Meta")
}

func init() {
	proto.RegisterFile("oswee/core/event/proto/v1/event.proto", fileDescriptor_3a56999bb3a91d08)
}

var fileDescriptor_3a56999bb3a91d08 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xc9, 0xff, 0x9f, 0x5a, 0x33, 0xa9, 0x1e, 0xd6, 0x4b, 0x52, 0x11, 0x6b, 0xa1, 0xd0,
	0x8b, 0xbb, 0x44, 0x8f, 0xde, 0x04, 0x0f, 0x3d, 0x08, 0xb2, 0xf4, 0xe4, 0x45, 0x36, 0xcd, 0xb8,
	0x04, 0x1a, 0x77, 0x49, 0xb6, 0x91, 0x7c, 0x42, 0xbf, 0x96, 0xec, 0x2c, 0xa9, 0x07, 0x3d, 0xbe,
	0x37, 0xbf, 0xf7, 0x60, 0x1e, 0xac, 0x4c, 0xf7, 0x89, 0x28, 0x76, 0xa6, 0x45, 0x81, 0x3d, 0x7e,
	0x38, 0x61, 0x5b, 0xe3, 0x8c, 0xe8, 0x8b, 0x20, 0x39, 0x49, 0x76, 0x41, 0x18, 0xf7, 0x18, 0x0f,
	0x7e, 0x5f, 0xcc, 0xaf, 0xb5, 0x31, 0x7a, 0x8f, 0x21, 0x51, 0x1e, 0xde, 0x85, 0xab, 0x1b, 0xec,
	0x9c, 0x6a, 0x6c, 0x48, 0x2d, 0x5f, 0x60, 0xf2, 0xe4, 0x61, 0x76, 0x0b, 0x71, 0x83, 0x4e, 0x65,
	0xd1, 0x22, 0x5a, 0xa7, 0x77, 0x39, 0xff, 0xa3, 0x8d, 0x3f, 0xa3, 0x53, 0x92, 0x30, 0x96, 0xc1,
	0xd4, 0xaa, 0x61, 0x6f, 0x54, 0x95, 0xfd, 0x5b, 0x44, 0xeb, 0x99, 0x1c, 0xe5, 0xf2, 0x2b, 0x82,
	0xd8, 0x83, 0x2c, 0x87, 0x53, 0x4a, 0xbe, 0xd5, 0x15, 0xb5, 0x26, 0x72, 0x4a, 0x7a, 0x53, 0xb1,
	0x2b, 0x80, 0x70, 0x72, 0x83, 0x45, 0x2a, 0x48, 0x64, 0x42, 0xce, 0x76, 0xb0, 0xc8, 0x6e, 0x60,
	0xa6, 0xb4, 0x6e, 0x51, 0x2b, 0x87, 0x3e, 0xfd, 0x9f, 0x80, 0xf4, 0xe8, 0x6d, 0x2a, 0xb6, 0x82,
	0xf3, 0x1f, 0x84, 0x5a, 0x62, 0x82, 0xce, 0x8e, 0x2e, 0x35, 0x3d, 0x40, 0xba, 0x6b, 0x91, 0x98,
	0xba, 0xc1, 0x6c, 0x42, 0xcf, 0xcd, 0x79, 0x58, 0x85, 0x8f, 0xab, 0xf0, 0xed, 0xb8, 0x8a, 0x84,
	0x80, 0x7b, 0xe3, 0xf1, 0xf2, 0x35, 0xff, 0x35, 0x7d, 0xe7, 0x0e, 0x65, 0x27, 0xfa, 0xa2, 0x3c,
	0xa1, 0xf0, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x18, 0xfb, 0xf0, 0x9e, 0x01, 0x00,
	0x00,
}
