// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderEntityStatus int32

const (
	OrderEntityStatus_ORDER_ENTITY_STATUS_INVALID  OrderEntityStatus = 0
	OrderEntityStatus_ORDER_ENTITY_STATUS_UNSET    OrderEntityStatus = 1
	OrderEntityStatus_ORDER_ENTITY_STATUS_VALID    OrderEntityStatus = 2
	OrderEntityStatus_ORDER_ENTITY_STATUS_REJECTED OrderEntityStatus = 3
)

var OrderEntityStatus_name = map[int32]string{
	0: "ORDER_ENTITY_STATUS_INVALID",
	1: "ORDER_ENTITY_STATUS_UNSET",
	2: "ORDER_ENTITY_STATUS_VALID",
	3: "ORDER_ENTITY_STATUS_REJECTED",
}

var OrderEntityStatus_value = map[string]int32{
	"ORDER_ENTITY_STATUS_INVALID":  0,
	"ORDER_ENTITY_STATUS_UNSET":    1,
	"ORDER_ENTITY_STATUS_VALID":    2,
	"ORDER_ENTITY_STATUS_REJECTED": 3,
}

func (x OrderEntityStatus) String() string {
	return proto.EnumName(OrderEntityStatus_name, int32(x))
}

func (OrderEntityStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

// Incomming Order request body
type Order struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Order) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Order) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type OrderEntity struct {
	Uuid                 []byte               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName          string               `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status               OrderEntityStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=oswee.shipping.orders.v1.OrderEntityStatus" json:"status,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderEntity) Reset()         { *m = OrderEntity{} }
func (m *OrderEntity) String() string { return proto.CompactTextString(m) }
func (*OrderEntity) ProtoMessage()    {}
func (*OrderEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderEntity.Unmarshal(m, b)
}
func (m *OrderEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderEntity.Marshal(b, m, deterministic)
}
func (m *OrderEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderEntity.Merge(m, src)
}
func (m *OrderEntity) XXX_Size() int {
	return xxx_messageInfo_OrderEntity.Size(m)
}
func (m *OrderEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderEntity.DiscardUnknown(m)
}

var xxx_messageInfo_OrderEntity proto.InternalMessageInfo

func (m *OrderEntity) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *OrderEntity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OrderEntity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *OrderEntity) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *OrderEntity) GetStatus() OrderEntityStatus {
	if m != nil {
		return m.Status
	}
	return OrderEntityStatus_ORDER_ENTITY_STATUS_INVALID
}

func (m *OrderEntity) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *OrderEntity) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("oswee.shipping.orders.v1.OrderEntityStatus", OrderEntityStatus_name, OrderEntityStatus_value)
	proto.RegisterType((*Order)(nil), "oswee.shipping.orders.v1.Order")
	proto.RegisterType((*OrderEntity)(nil), "oswee.shipping.orders.v1.OrderEntity")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0xc5, 0x49, 0x13, 0xc0, 0x53, 0xa1, 0x60, 0xb1, 0x18, 0xc2, 0xa3, 0xa6, 0xab, 0xa8, 0x50,
	0x5b, 0x0d, 0x3b, 0x58, 0x85, 0xc4, 0x12, 0x41, 0x28, 0x95, 0x26, 0x53, 0x24, 0xd8, 0x8c, 0x9c,
	0x8c, 0x3b, 0x58, 0xca, 0xd8, 0x23, 0xdb, 0xd3, 0xa8, 0xbf, 0x81, 0xf8, 0x06, 0xfe, 0x80, 0x1f,
	0xc9, 0x17, 0xa1, 0xb1, 0x9b, 0x02, 0x6a, 0xa3, 0xee, 0x7c, 0xef, 0x39, 0xe7, 0xfa, 0x9e, 0x7b,
	0x60, 0xa4, 0x4d, 0x2e, 0x0c, 0xa9, 0x8c, 0x76, 0x1a, 0xc5, 0xda, 0xae, 0x85, 0x20, 0xf6, 0xbb,
	0xac, 0x2a, 0xa9, 0x0a, 0xe2, 0x31, 0x4b, 0x2e, 0x4e, 0xfa, 0x6f, 0x3c, 0x61, 0x79, 0x5c, 0x08,
	0x75, 0x6c, 0xd7, 0xbc, 0x28, 0x84, 0xa1, 0xba, 0x72, 0x52, 0x2b, 0x4b, 0xb9, 0x52, 0xda, 0x71,
	0xff, 0x0e, 0x73, 0xfa, 0x07, 0x85, 0xd6, 0xc5, 0x4a, 0x50, 0x5f, 0x2d, 0xea, 0x73, 0xea, 0x64,
	0x29, 0xac, 0xe3, 0x65, 0x15, 0x08, 0x87, 0xbf, 0x00, 0xec, 0x9c, 0x36, 0xc3, 0xd1, 0x13, 0xd8,
	0x11, 0x25, 0x97, 0xab, 0x18, 0x60, 0x30, 0x78, 0x98, 0x84, 0x02, 0xf5, 0xe1, 0x83, 0x8a, 0x5b,
	0xbb, 0xd6, 0x26, 0x8f, 0x5b, 0x1e, 0xb8, 0xae, 0xd1, 0x2b, 0xb8, 0x9f, 0x4b, 0x5b, 0xad, 0xf8,
	0x65, 0xa6, 0x78, 0x29, 0xe2, 0xb6, 0xc7, 0xa3, 0xab, 0xde, 0x8c, 0x97, 0xe2, 0xdd, 0xc7, 0x1f,
	0x23, 0x06, 0xc7, 0x47, 0xe1, 0x8b, 0x61, 0x3c, 0x11, 0xe7, 0x52, 0x09, 0xcc, 0xb1, 0xaf, 0xb1,
	0x75, 0xa6, 0x5e, 0xba, 0xda, 0x88, 0x0d, 0x08, 0xdf, 0x6d, 0xc0, 0xf5, 0xf4, 0x0d, 0xf8, 0x6f,
	0xf8, 0xe1, 0xef, 0x16, 0x8c, 0xbc, 0x8a, 0x29, 0x27, 0xdd, 0x25, 0x42, 0x70, 0xaf, 0xae, 0x65,
	0xee, 0xb7, 0xdd, 0x4f, 0xfc, 0xfb, 0xaf, 0x85, 0xd6, 0x2e, 0x0b, 0xed, 0x3b, 0x2c, 0xec, 0xdd,
	0xb0, 0x80, 0xc6, 0xb0, 0x6b, 0x1d, 0x77, 0xb5, 0x8d, 0x3b, 0x18, 0x0c, 0x1e, 0x0d, 0x5f, 0x93,
	0x5d, 0xd9, 0x90, 0x7f, 0xf6, 0x9b, 0x7b, 0x49, 0x72, 0x25, 0x45, 0xef, 0x61, 0x14, 0x5e, 0x59,
	0x13, 0x40, 0xdc, 0xc5, 0x60, 0x10, 0x0d, 0xfb, 0x24, 0xa4, 0x43, 0xb6, 0xe9, 0x90, 0x74, 0x9b,
	0x4e, 0x02, 0x03, 0xbd, 0x69, 0x34, 0xe2, 0xa5, 0x11, 0xdc, 0x89, 0x20, 0xbe, 0x7f, 0xb7, 0x38,
	0xd0, 0x9b, 0xc6, 0xd1, 0x4f, 0x00, 0x1f, 0xdf, 0xd8, 0x0b, 0x1d, 0xc0, 0x67, 0xa7, 0xc9, 0x84,
	0x25, 0x19, 0x9b, 0xa5, 0xd3, 0xf4, 0x6b, 0x36, 0x4f, 0x47, 0xe9, 0xd9, 0x3c, 0x9b, 0xce, 0xbe,
	0x8c, 0x3e, 0x4f, 0x27, 0xbd, 0x7b, 0xe8, 0x05, 0x7c, 0x7a, 0x1b, 0xe1, 0x6c, 0x36, 0x67, 0x69,
	0x0f, 0xec, 0x82, 0x83, 0xba, 0x85, 0x30, 0x7c, 0x7e, 0x1b, 0x9c, 0xb0, 0x4f, 0x6c, 0x9c, 0xb2,
	0x49, 0xaf, 0xfd, 0x01, 0x7f, 0x7b, 0xe9, 0xcf, 0x48, 0xb7, 0x67, 0xa4, 0xe1, 0x8c, 0xd4, 0xba,
	0x7a, 0x61, 0xe9, 0xc5, 0xc9, 0xa2, 0xeb, 0x8d, 0xbd, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x14,
	0x8d, 0xa0, 0xa9, 0x18, 0x03, 0x00, 0x00,
}
