// source: module.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.oswee.module.v1.Envelope', null, global);
goog.exportSymbol('proto.oswee.module.v1.Envelope.KindCase', null, global);
goog.exportSymbol('proto.oswee.module.v1.ListModulesRequest', null, global);
goog.exportSymbol('proto.oswee.module.v1.ListModulesResponse', null, global);
goog.exportSymbol('proto.oswee.module.v1.Module', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oswee.module.v1.Module = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oswee.module.v1.Module, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oswee.module.v1.Module.displayName = 'proto.oswee.module.v1.Module';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oswee.module.v1.ListModulesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.oswee.module.v1.ListModulesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oswee.module.v1.ListModulesRequest.displayName = 'proto.oswee.module.v1.ListModulesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oswee.module.v1.ListModulesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.oswee.module.v1.ListModulesResponse.repeatedFields_, null);
};
goog.inherits(proto.oswee.module.v1.ListModulesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oswee.module.v1.ListModulesResponse.displayName = 'proto.oswee.module.v1.ListModulesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oswee.module.v1.Envelope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.oswee.module.v1.Envelope.oneofGroups_);
};
goog.inherits(proto.oswee.module.v1.Envelope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oswee.module.v1.Envelope.displayName = 'proto.oswee.module.v1.Envelope';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oswee.module.v1.Module.prototype.toObject = function(opt_includeInstance) {
  return proto.oswee.module.v1.Module.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oswee.module.v1.Module} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.Module.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    permalink: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oswee.module.v1.Module}
 */
proto.oswee.module.v1.Module.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oswee.module.v1.Module;
  return proto.oswee.module.v1.Module.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oswee.module.v1.Module} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oswee.module.v1.Module}
 */
proto.oswee.module.v1.Module.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPermalink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oswee.module.v1.Module.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oswee.module.v1.Module.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oswee.module.v1.Module} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.Module.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPermalink();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.oswee.module.v1.Module.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.oswee.module.v1.Module} returns this
 */
proto.oswee.module.v1.Module.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.oswee.module.v1.Module.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.oswee.module.v1.Module} returns this
 */
proto.oswee.module.v1.Module.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string permalink = 3;
 * @return {string}
 */
proto.oswee.module.v1.Module.prototype.getPermalink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.oswee.module.v1.Module} returns this
 */
proto.oswee.module.v1.Module.prototype.setPermalink = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oswee.module.v1.ListModulesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.oswee.module.v1.ListModulesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oswee.module.v1.ListModulesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.ListModulesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oswee.module.v1.ListModulesRequest}
 */
proto.oswee.module.v1.ListModulesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oswee.module.v1.ListModulesRequest;
  return proto.oswee.module.v1.ListModulesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oswee.module.v1.ListModulesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oswee.module.v1.ListModulesRequest}
 */
proto.oswee.module.v1.ListModulesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oswee.module.v1.ListModulesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oswee.module.v1.ListModulesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oswee.module.v1.ListModulesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.ListModulesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.oswee.module.v1.ListModulesRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.oswee.module.v1.ListModulesRequest} returns this
 */
proto.oswee.module.v1.ListModulesRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.oswee.module.v1.ListModulesResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oswee.module.v1.ListModulesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.oswee.module.v1.ListModulesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oswee.module.v1.ListModulesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.ListModulesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    entitiesMap: (f = msg.getEntitiesMap()) ? f.toObject(includeInstance, proto.oswee.module.v1.Module.toObject) : [],
    idsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oswee.module.v1.ListModulesResponse}
 */
proto.oswee.module.v1.ListModulesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oswee.module.v1.ListModulesResponse;
  return proto.oswee.module.v1.ListModulesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oswee.module.v1.ListModulesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oswee.module.v1.ListModulesResponse}
 */
proto.oswee.module.v1.ListModulesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getEntitiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.oswee.module.v1.Module.deserializeBinaryFromReader, "", new proto.oswee.module.v1.Module());
         });
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oswee.module.v1.ListModulesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oswee.module.v1.ListModulesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oswee.module.v1.ListModulesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.ListModulesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntitiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.oswee.module.v1.Module.serializeBinaryToWriter);
  }
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * map<string, Module> entities = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.oswee.module.v1.Module>}
 */
proto.oswee.module.v1.ListModulesResponse.prototype.getEntitiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.oswee.module.v1.Module>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.oswee.module.v1.Module));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.oswee.module.v1.ListModulesResponse} returns this
 */
proto.oswee.module.v1.ListModulesResponse.prototype.clearEntitiesMap = function() {
  this.getEntitiesMap().clear();
  return this;};


/**
 * repeated string ids = 2;
 * @return {!Array<string>}
 */
proto.oswee.module.v1.ListModulesResponse.prototype.getIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.oswee.module.v1.ListModulesResponse} returns this
 */
proto.oswee.module.v1.ListModulesResponse.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.oswee.module.v1.ListModulesResponse} returns this
 */
proto.oswee.module.v1.ListModulesResponse.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oswee.module.v1.ListModulesResponse} returns this
 */
proto.oswee.module.v1.ListModulesResponse.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.oswee.module.v1.Envelope.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.oswee.module.v1.Envelope.KindCase = {
  KIND_NOT_SET: 0,
  A: 1,
  B: 2
};

/**
 * @return {proto.oswee.module.v1.Envelope.KindCase}
 */
proto.oswee.module.v1.Envelope.prototype.getKindCase = function() {
  return /** @type {proto.oswee.module.v1.Envelope.KindCase} */(jspb.Message.computeOneofCase(this, proto.oswee.module.v1.Envelope.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oswee.module.v1.Envelope.prototype.toObject = function(opt_includeInstance) {
  return proto.oswee.module.v1.Envelope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oswee.module.v1.Envelope} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.Envelope.toObject = function(includeInstance, msg) {
  var f, obj = {
    a: (f = msg.getA()) && proto.oswee.module.v1.ListModulesRequest.toObject(includeInstance, f),
    b: (f = msg.getB()) && proto.oswee.module.v1.ListModulesResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oswee.module.v1.Envelope}
 */
proto.oswee.module.v1.Envelope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oswee.module.v1.Envelope;
  return proto.oswee.module.v1.Envelope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oswee.module.v1.Envelope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oswee.module.v1.Envelope}
 */
proto.oswee.module.v1.Envelope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.oswee.module.v1.ListModulesRequest;
      reader.readMessage(value,proto.oswee.module.v1.ListModulesRequest.deserializeBinaryFromReader);
      msg.setA(value);
      break;
    case 2:
      var value = new proto.oswee.module.v1.ListModulesResponse;
      reader.readMessage(value,proto.oswee.module.v1.ListModulesResponse.deserializeBinaryFromReader);
      msg.setB(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oswee.module.v1.Envelope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oswee.module.v1.Envelope.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oswee.module.v1.Envelope} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oswee.module.v1.Envelope.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getA();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.oswee.module.v1.ListModulesRequest.serializeBinaryToWriter
    );
  }
  f = message.getB();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.oswee.module.v1.ListModulesResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ListModulesRequest a = 1;
 * @return {?proto.oswee.module.v1.ListModulesRequest}
 */
proto.oswee.module.v1.Envelope.prototype.getA = function() {
  return /** @type{?proto.oswee.module.v1.ListModulesRequest} */ (
    jspb.Message.getWrapperField(this, proto.oswee.module.v1.ListModulesRequest, 1));
};


/**
 * @param {?proto.oswee.module.v1.ListModulesRequest|undefined} value
 * @return {!proto.oswee.module.v1.Envelope} returns this
*/
proto.oswee.module.v1.Envelope.prototype.setA = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.oswee.module.v1.Envelope.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oswee.module.v1.Envelope} returns this
 */
proto.oswee.module.v1.Envelope.prototype.clearA = function() {
  return this.setA(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oswee.module.v1.Envelope.prototype.hasA = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ListModulesResponse b = 2;
 * @return {?proto.oswee.module.v1.ListModulesResponse}
 */
proto.oswee.module.v1.Envelope.prototype.getB = function() {
  return /** @type{?proto.oswee.module.v1.ListModulesResponse} */ (
    jspb.Message.getWrapperField(this, proto.oswee.module.v1.ListModulesResponse, 2));
};


/**
 * @param {?proto.oswee.module.v1.ListModulesResponse|undefined} value
 * @return {!proto.oswee.module.v1.Envelope} returns this
*/
proto.oswee.module.v1.Envelope.prototype.setB = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.oswee.module.v1.Envelope.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oswee.module.v1.Envelope} returns this
 */
proto.oswee.module.v1.Envelope.prototype.clearB = function() {
  return this.setB(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oswee.module.v1.Envelope.prototype.hasB = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.oswee.module.v1);
