// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/identity/signup/proto/v1/signup_event_handler.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupValidatedRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Signup               *SignupEntity        `protobuf:"bytes,2,opt,name=signup,proto3" json:"signup,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignupValidatedRequest) Reset()         { *m = SignupValidatedRequest{} }
func (m *SignupValidatedRequest) String() string { return proto.CompactTextString(m) }
func (*SignupValidatedRequest) ProtoMessage()    {}
func (*SignupValidatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65784bf58f34f584, []int{0}
}

func (m *SignupValidatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupValidatedRequest.Unmarshal(m, b)
}
func (m *SignupValidatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupValidatedRequest.Marshal(b, m, deterministic)
}
func (m *SignupValidatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupValidatedRequest.Merge(m, src)
}
func (m *SignupValidatedRequest) XXX_Size() int {
	return xxx_messageInfo_SignupValidatedRequest.Size(m)
}
func (m *SignupValidatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupValidatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupValidatedRequest proto.InternalMessageInfo

func (m *SignupValidatedRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SignupValidatedRequest) GetSignup() *SignupEntity {
	if m != nil {
		return m.Signup
	}
	return nil
}

func (m *SignupValidatedRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupValidatedRequest)(nil), "oswee.identity.signup.v1.SignupValidatedRequest")
}

func init() {
	proto.RegisterFile("oswee/identity/signup/proto/v1/signup_event_handler.proto", fileDescriptor_65784bf58f34f584)
}

var fileDescriptor_65784bf58f34f584 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xa9, 0x0b, 0x0b, 0x66, 0x0f, 0x4a, 0x0e, 0x4b, 0xad, 0xa0, 0x8b, 0x07, 0x59, 0x10,
	0x12, 0xbb, 0x9e, 0x44, 0xf0, 0x20, 0x2c, 0x78, 0xee, 0x8a, 0x07, 0x3d, 0x94, 0x74, 0x3b, 0xd6,
	0x40, 0xff, 0xc4, 0x66, 0x1a, 0xdd, 0x4f, 0xe4, 0xd7, 0x94, 0x24, 0xed, 0xa5, 0x2a, 0x7a, 0x4b,
	0x66, 0xde, 0x7b, 0xcc, 0xef, 0x91, 0xeb, 0x46, 0xbf, 0x03, 0x70, 0x99, 0x43, 0x8d, 0x12, 0x77,
	0x5c, 0xcb, 0xa2, 0xee, 0x14, 0x57, 0x6d, 0x83, 0x0d, 0x37, 0x71, 0xff, 0x4f, 0xc1, 0x40, 0x8d,
	0xe9, 0xab, 0xa8, 0xf3, 0x12, 0x5a, 0xe6, 0xb6, 0x34, 0x74, 0x56, 0x36, 0x58, 0x99, 0x97, 0x32,
	0x13, 0x47, 0xa7, 0x45, 0xd3, 0x14, 0x25, 0xf8, 0x94, 0xac, 0x7b, 0xe1, 0x28, 0x2b, 0xd0, 0x28,
	0x2a, 0xe5, 0xad, 0xd1, 0xf1, 0x58, 0x00, 0x95, 0xc2, 0x5d, 0xbf, 0xbc, 0xf8, 0xd7, 0x49, 0x5e,
	0x7c, 0xf6, 0x19, 0x90, 0xf9, 0xc6, 0x0d, 0x1e, 0x45, 0x29, 0x73, 0x81, 0x90, 0x27, 0xf0, 0xd6,
	0x81, 0x46, 0x7a, 0x48, 0x26, 0x42, 0xc9, 0x30, 0x58, 0x04, 0xcb, 0xfd, 0xc4, 0x3e, 0xe9, 0x2d,
	0x99, 0x7a, 0x73, 0xb8, 0xb7, 0x08, 0x96, 0xb3, 0xd5, 0x39, 0xfb, 0x0d, 0x81, 0xf9, 0xcc, 0xb5,
	0x1b, 0x27, 0xbd, 0x8b, 0xde, 0x90, 0xd9, 0xb6, 0x05, 0x81, 0x90, 0x5a, 0xa0, 0x70, 0xe2, 0x42,
	0x22, 0xe6, 0x61, 0xd8, 0x00, 0xc3, 0x1e, 0x06, 0xda, 0x84, 0x78, 0xb9, 0x1d, 0xac, 0x3e, 0xc8,
	0x51, 0x1f, 0x6a, 0xbb, 0xbc, 0xf7, 0x55, 0x6e, 0xa0, 0x35, 0x72, 0x0b, 0xf4, 0x99, 0x1c, 0x8c,
	0x28, 0xe8, 0xe5, 0x5f, 0xc7, 0x8d, 0x81, 0xa3, 0xf9, 0xb7, 0x4b, 0xd6, 0xb6, 0xd6, 0xbb, 0xc5,
	0xd3, 0xc9, 0xcf, 0x95, 0x6a, 0xec, 0x32, 0xcd, 0x4d, 0x9c, 0x4d, 0x9d, 0xe3, 0xea, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x75, 0x77, 0x9f, 0x30, 0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupEventHandlerServiceClient is the client API for SignupEventHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupEventHandlerServiceClient interface {
	SignupValidated(ctx context.Context, in *SignupValidatedRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type signupEventHandlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupEventHandlerServiceClient(cc *grpc.ClientConn) SignupEventHandlerServiceClient {
	return &signupEventHandlerServiceClient{cc}
}

func (c *signupEventHandlerServiceClient) SignupValidated(ctx context.Context, in *SignupValidatedRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/oswee.identity.signup.v1.SignupEventHandlerService/SignupValidated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupEventHandlerServiceServer is the server API for SignupEventHandlerService service.
type SignupEventHandlerServiceServer interface {
	SignupValidated(context.Context, *SignupValidatedRequest) (*empty.Empty, error)
}

// UnimplementedSignupEventHandlerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignupEventHandlerServiceServer struct {
}

func (*UnimplementedSignupEventHandlerServiceServer) SignupValidated(ctx context.Context, req *SignupValidatedRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupValidated not implemented")
}

func RegisterSignupEventHandlerServiceServer(s *grpc.Server, srv SignupEventHandlerServiceServer) {
	s.RegisterService(&_SignupEventHandlerService_serviceDesc, srv)
}

func _SignupEventHandlerService_SignupValidated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupValidatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupEventHandlerServiceServer).SignupValidated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.identity.signup.v1.SignupEventHandlerService/SignupValidated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupEventHandlerServiceServer).SignupValidated(ctx, req.(*SignupValidatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupEventHandlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.identity.signup.v1.SignupEventHandlerService",
	HandlerType: (*SignupEventHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignupValidated",
			Handler:    _SignupEventHandlerService_SignupValidated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oswee/identity/signup/proto/v1/signup_event_handler.proto",
}
