// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/identity/signup/proto/v1/signup_command_handler.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Signup               *Signup              `protobuf:"bytes,2,opt,name=signup,proto3" json:"signup,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3853b9605670ad17, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetSignup() *Signup {
	if m != nil {
		return m.Signup
	}
	return nil
}

func (m *CreateRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "oswee.identity.signup.v1.CreateRequest")
}

func init() {
	proto.RegisterFile("oswee/identity/signup/proto/v1/signup_command_handler.proto", fileDescriptor_3853b9605670ad17)
}

var fileDescriptor_3853b9605670ad17 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x85, 0x8a, 0x5b, 0x04, 0xd9, 0x83, 0x84, 0x14, 0x34, 0x78, 0xb1, 0x20, 0xec,
	0xd2, 0x7a, 0x11, 0x7a, 0xb3, 0x08, 0xe2, 0x49, 0x52, 0x4f, 0x5e, 0x42, 0xfe, 0x8c, 0xe9, 0x42,
	0x36, 0xbb, 0x66, 0x77, 0x23, 0xfd, 0x26, 0x7e, 0x5c, 0xc9, 0x4e, 0x72, 0xf0, 0x4f, 0xc1, 0xdb,
	0x24, 0xf3, 0x7e, 0xb3, 0xef, 0x3d, 0xb2, 0x56, 0xe6, 0x03, 0x80, 0x8b, 0x12, 0x1a, 0x2b, 0xec,
	0x9e, 0x1b, 0x51, 0x35, 0x4e, 0x73, 0xdd, 0x2a, 0xab, 0x78, 0xb7, 0x1c, 0xbe, 0xd3, 0x42, 0x49,
	0x99, 0x35, 0x65, 0xba, 0xcb, 0x9a, 0xb2, 0x86, 0x96, 0xf9, 0x3d, 0x0d, 0x3d, 0xcc, 0x46, 0x98,
	0xa1, 0x98, 0x75, 0xcb, 0xe8, 0xb2, 0x52, 0xaa, 0xaa, 0x01, 0xef, 0xe4, 0xee, 0x8d, 0x5b, 0x21,
	0xc1, 0xd8, 0x4c, 0x6a, 0x44, 0xa3, 0xf9, 0x4f, 0x01, 0x48, 0x6d, 0xf7, 0xc3, 0xf2, 0xe6, 0x5f,
	0xa6, 0x50, 0x7c, 0xf5, 0x19, 0x90, 0xd3, 0x4d, 0x0b, 0x99, 0x85, 0x04, 0xde, 0x1d, 0x18, 0x4b,
	0xcf, 0xc8, 0x24, 0xd3, 0x22, 0x0c, 0xe2, 0x60, 0x71, 0x92, 0xf4, 0x23, 0xbd, 0x23, 0x53, 0x64,
	0xc2, 0xa3, 0x38, 0x58, 0xcc, 0x56, 0x31, 0x3b, 0xe4, 0x9c, 0x6d, 0xfd, 0x94, 0x0c, 0x7a, 0xba,
	0x26, 0xb3, 0xc2, 0x1f, 0x4f, 0xfb, 0x04, 0xe1, 0xc4, 0xe3, 0x11, 0x43, 0xf7, 0x6c, 0x74, 0xcf,
	0x5e, 0xc6, 0x78, 0x09, 0x41, 0x79, 0xff, 0x63, 0x25, 0xc8, 0x1c, 0xcf, 0x6d, 0xb0, 0xbe, 0x47,
	0x6c, 0x6f, 0x0b, 0x6d, 0x27, 0x0a, 0xa0, 0x4f, 0xe4, 0xf8, 0xd9, 0xe5, 0xb5, 0x30, 0x3b, 0x7a,
	0x7d, 0xd8, 0xd0, 0xb7, 0x6c, 0xd1, 0xf9, 0xaf, 0xa7, 0x1f, 0xfa, 0xe2, 0xee, 0xe3, 0xd7, 0x8b,
	0xbf, 0x4b, 0x33, 0xd6, 0xe5, 0x86, 0x77, 0xcb, 0x7c, 0xea, 0x89, 0xdb, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x83, 0xfa, 0x42, 0xdb, 0xf2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupCommandHandlerServiceClient is the client API for SignupCommandHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupCommandHandlerServiceClient interface {
	Publish(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type signupCommandHandlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupCommandHandlerServiceClient(cc *grpc.ClientConn) SignupCommandHandlerServiceClient {
	return &signupCommandHandlerServiceClient{cc}
}

func (c *signupCommandHandlerServiceClient) Publish(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/oswee.identity.signup.v1.SignupCommandHandlerService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupCommandHandlerServiceServer is the server API for SignupCommandHandlerService service.
type SignupCommandHandlerServiceServer interface {
	Publish(context.Context, *CreateRequest) (*empty.Empty, error)
}

// UnimplementedSignupCommandHandlerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignupCommandHandlerServiceServer struct {
}

func (*UnimplementedSignupCommandHandlerServiceServer) Publish(ctx context.Context, req *CreateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterSignupCommandHandlerServiceServer(s *grpc.Server, srv SignupCommandHandlerServiceServer) {
	s.RegisterService(&_SignupCommandHandlerService_serviceDesc, srv)
}

func _SignupCommandHandlerService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupCommandHandlerServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.identity.signup.v1.SignupCommandHandlerService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupCommandHandlerServiceServer).Publish(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupCommandHandlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.identity.signup.v1.SignupCommandHandlerService",
	HandlerType: (*SignupCommandHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _SignupCommandHandlerService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oswee/identity/signup/proto/v1/signup_command_handler.proto",
}
