// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/identity/signup/proto/v1/signup.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupEntityStatus int32

const (
	SignupEntityStatus_SIGNUP_ENTITY_STATUS_INVALID  SignupEntityStatus = 0
	SignupEntityStatus_SIGNUP_ENTITY_STATUS_UNSET    SignupEntityStatus = 1
	SignupEntityStatus_SIGNUP_ENTITY_STATUS_VALID    SignupEntityStatus = 2
	SignupEntityStatus_SIGNUP_ENTITY_STATUS_REJECTED SignupEntityStatus = 3
)

var SignupEntityStatus_name = map[int32]string{
	0: "SIGNUP_ENTITY_STATUS_INVALID",
	1: "SIGNUP_ENTITY_STATUS_UNSET",
	2: "SIGNUP_ENTITY_STATUS_VALID",
	3: "SIGNUP_ENTITY_STATUS_REJECTED",
}

var SignupEntityStatus_value = map[string]int32{
	"SIGNUP_ENTITY_STATUS_INVALID":  0,
	"SIGNUP_ENTITY_STATUS_UNSET":    1,
	"SIGNUP_ENTITY_STATUS_VALID":    2,
	"SIGNUP_ENTITY_STATUS_REJECTED": 3,
}

func (x SignupEntityStatus) String() string {
	return proto.EnumName(SignupEntityStatus_name, int32(x))
}

func (SignupEntityStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98fc74e7cad9fd9d, []int{0}
}

// Incomming Signup request body
type Signup struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signup) Reset()         { *m = Signup{} }
func (m *Signup) String() string { return proto.CompactTextString(m) }
func (*Signup) ProtoMessage()    {}
func (*Signup) Descriptor() ([]byte, []int) {
	return fileDescriptor_98fc74e7cad9fd9d, []int{0}
}

func (m *Signup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signup.Unmarshal(m, b)
}
func (m *Signup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signup.Marshal(b, m, deterministic)
}
func (m *Signup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signup.Merge(m, src)
}
func (m *Signup) XXX_Size() int {
	return xxx_messageInfo_Signup.Size(m)
}
func (m *Signup) XXX_DiscardUnknown() {
	xxx_messageInfo_Signup.DiscardUnknown(m)
}

var xxx_messageInfo_Signup proto.InternalMessageInfo

func (m *Signup) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Signup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Signup) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type SignupEntity struct {
	Uuid                 []byte               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName          string               `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status               SignupEntityStatus   `protobuf:"varint,5,opt,name=status,proto3,enum=oswee.identity.signup.v1.SignupEntityStatus" json:"status,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignupEntity) Reset()         { *m = SignupEntity{} }
func (m *SignupEntity) String() string { return proto.CompactTextString(m) }
func (*SignupEntity) ProtoMessage()    {}
func (*SignupEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_98fc74e7cad9fd9d, []int{1}
}

func (m *SignupEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupEntity.Unmarshal(m, b)
}
func (m *SignupEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupEntity.Marshal(b, m, deterministic)
}
func (m *SignupEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupEntity.Merge(m, src)
}
func (m *SignupEntity) XXX_Size() int {
	return xxx_messageInfo_SignupEntity.Size(m)
}
func (m *SignupEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupEntity.DiscardUnknown(m)
}

var xxx_messageInfo_SignupEntity proto.InternalMessageInfo

func (m *SignupEntity) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *SignupEntity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupEntity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignupEntity) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SignupEntity) GetStatus() SignupEntityStatus {
	if m != nil {
		return m.Status
	}
	return SignupEntityStatus_SIGNUP_ENTITY_STATUS_INVALID
}

func (m *SignupEntity) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *SignupEntity) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("oswee.identity.signup.v1.SignupEntityStatus", SignupEntityStatus_name, SignupEntityStatus_value)
	proto.RegisterType((*Signup)(nil), "oswee.identity.signup.v1.Signup")
	proto.RegisterType((*SignupEntity)(nil), "oswee.identity.signup.v1.SignupEntity")
}

func init() {
	proto.RegisterFile("oswee/identity/signup/proto/v1/signup.proto", fileDescriptor_98fc74e7cad9fd9d)
}

var fileDescriptor_98fc74e7cad9fd9d = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0xc5, 0xed, 0x56, 0xc0, 0xad, 0x50, 0x65, 0xf1, 0x10, 0x22, 0x18, 0xd9, 0x9e, 0xaa, 0xb1,
	0xd9, 0x6a, 0x79, 0x83, 0xa7, 0x42, 0xa3, 0xa9, 0x13, 0x8a, 0x50, 0x92, 0x22, 0xc1, 0x4b, 0xe4,
	0xb6, 0x5e, 0x64, 0xa9, 0xb1, 0xa3, 0xd8, 0x6e, 0xb5, 0xdf, 0xe0, 0x8d, 0x4f, 0xe0, 0x0b, 0xf8,
	0x8f, 0x7e, 0x11, 0x8a, 0x9d, 0x0e, 0xa6, 0xb5, 0xda, 0x9b, 0xef, 0xbd, 0xe7, 0x9c, 0x7b, 0x4f,
	0x8e, 0x02, 0xdf, 0x49, 0xb5, 0x61, 0x8c, 0xf0, 0x25, 0x13, 0x9a, 0xeb, 0x5b, 0xa2, 0x78, 0x2e,
	0x4c, 0x49, 0xca, 0x4a, 0x6a, 0x49, 0xd6, 0xc3, 0xa6, 0xc6, 0xb6, 0x46, 0x9e, 0x05, 0xe3, 0x1d,
	0x18, 0x37, 0xc3, 0xf5, 0xd0, 0xbf, 0xb0, 0x80, 0xc5, 0x65, 0xce, 0xc4, 0xa5, 0xda, 0xd0, 0x3c,
	0x67, 0x15, 0x91, 0xa5, 0xe6, 0x52, 0x28, 0x42, 0x85, 0x90, 0x9a, 0xda, 0xb7, 0xd3, 0xf1, 0xdf,
	0xe6, 0x52, 0xe6, 0x2b, 0xe6, 0xb6, 0xcc, 0xcd, 0x0d, 0xd1, 0xbc, 0x60, 0x4a, 0xd3, 0xa2, 0x59,
	0x74, 0xf6, 0x1b, 0xc0, 0x4e, 0x62, 0xc5, 0xd1, 0x4b, 0x78, 0xcc, 0x0a, 0xca, 0x57, 0x1e, 0x08,
	0xc0, 0xe0, 0x79, 0xec, 0x0a, 0xe4, 0xc3, 0x67, 0x25, 0x55, 0x6a, 0x23, 0xab, 0xa5, 0xd7, 0xb2,
	0x83, 0xbb, 0x1a, 0x9d, 0xc2, 0xde, 0x92, 0xab, 0x72, 0x45, 0x6f, 0x33, 0x41, 0x0b, 0xe6, 0xb5,
	0xed, 0xbc, 0xdb, 0xf4, 0x22, 0x5a, 0xb0, 0x0f, 0xd7, 0x3f, 0xc7, 0x57, 0x30, 0x3c, 0x6f, 0x76,
	0x8c, 0x5e, 0x4d, 0xd8, 0x0d, 0x17, 0x2c, 0xa0, 0x41, 0xdd, 0x98, 0x95, 0x81, 0xd2, 0x95, 0x59,
	0x68, 0x53, 0xb1, 0x2d, 0x70, 0x0b, 0xb7, 0xe0, 0x4e, 0x7f, 0x0b, 0xee, 0xc9, 0x9f, 0xfd, 0x69,
	0xc1, 0x9e, 0xd3, 0x09, 0xed, 0x57, 0x41, 0x08, 0x1e, 0x19, 0xc3, 0x97, 0xf6, 0xe0, 0x5e, 0x6c,
	0xdf, 0xff, 0x5c, 0xb4, 0x0e, 0xb9, 0x68, 0x3f, 0xe2, 0xe2, 0xe8, 0x81, 0x0b, 0x34, 0x81, 0x1d,
	0xa5, 0xa9, 0x36, 0xca, 0x3b, 0x0e, 0xc0, 0xe0, 0xc5, 0xe8, 0x02, 0x1f, 0xca, 0x07, 0xff, 0x7f,
	0x60, 0x62, 0x39, 0x71, 0xc3, 0x45, 0x1f, 0x61, 0xd7, 0xbd, 0xb2, 0x3a, 0x05, 0xaf, 0x13, 0x80,
	0x41, 0x77, 0xe4, 0x63, 0x17, 0x11, 0xde, 0x45, 0x84, 0xd3, 0x5d, 0x44, 0x31, 0x74, 0xf0, 0xba,
	0x51, 0x93, 0x17, 0x15, 0xa3, 0x9a, 0x39, 0xf2, 0xd3, 0xc7, 0xc9, 0x0e, 0x5e, 0x37, 0xce, 0x7f,
	0x01, 0x88, 0x1e, 0x1e, 0x86, 0x02, 0xf8, 0x3a, 0x99, 0x5e, 0x45, 0xb3, 0xaf, 0x59, 0x18, 0xa5,
	0xd3, 0xf4, 0x7b, 0x96, 0xa4, 0xe3, 0x74, 0x96, 0x64, 0xd3, 0xe8, 0xdb, 0xf8, 0xcb, 0x74, 0xd2,
	0x7f, 0x82, 0x4e, 0xa0, 0xbf, 0x17, 0x31, 0x8b, 0x92, 0x30, 0xed, 0x83, 0x83, 0x73, 0xc7, 0x6f,
	0xa1, 0x53, 0xf8, 0x66, 0xef, 0x3c, 0x0e, 0xaf, 0xc3, 0xcf, 0x69, 0x38, 0xe9, 0xb7, 0x3f, 0x05,
	0x3f, 0x4e, 0xf6, 0xff, 0x19, 0x4a, 0x9b, 0xb9, 0x22, 0xeb, 0xe1, 0xbc, 0x63, 0xdd, 0xbd, 0xff,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xc9, 0xf3, 0xc0, 0x42, 0x03, 0x00, 0x00,
}
