// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/identity/signup/proto/v1/signup_projection.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProjectRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Signup               *SignupEntity        `protobuf:"bytes,2,opt,name=signup,proto3" json:"signup,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProjectRequest) Reset()         { *m = ProjectRequest{} }
func (m *ProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectRequest) ProtoMessage()    {}
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36dfee0d2c0430e4, []int{0}
}

func (m *ProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRequest.Unmarshal(m, b)
}
func (m *ProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRequest.Marshal(b, m, deterministic)
}
func (m *ProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRequest.Merge(m, src)
}
func (m *ProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectRequest.Size(m)
}
func (m *ProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRequest proto.InternalMessageInfo

func (m *ProjectRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProjectRequest) GetSignup() *SignupEntity {
	if m != nil {
		return m.Signup
	}
	return nil
}

func (m *ProjectRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*ProjectRequest)(nil), "oswee.identity.signup.v1.ProjectRequest")
}

func init() {
	proto.RegisterFile("oswee/identity/signup/proto/v1/signup_projection.proto", fileDescriptor_36dfee0d2c0430e4)
}

var fileDescriptor_36dfee0d2c0430e4 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xa9, 0x0b, 0x2b, 0x66, 0x41, 0x24, 0x07, 0x2d, 0x15, 0xb4, 0x78, 0x90, 0x82, 0x90,
	0xd0, 0x15, 0xbc, 0x08, 0x1e, 0x84, 0x3d, 0x79, 0x59, 0xba, 0x9e, 0xbc, 0x2c, 0x6d, 0x9d, 0x2d,
	0x11, 0xdb, 0xc4, 0x66, 0x5a, 0xd9, 0x4f, 0xe3, 0x57, 0x95, 0x66, 0x52, 0xc1, 0x3f, 0x0b, 0xde,
	0x26, 0x33, 0xef, 0x37, 0x79, 0x6f, 0xd8, 0x8d, 0xb6, 0xef, 0x00, 0x52, 0x3d, 0x43, 0x83, 0x0a,
	0xb7, 0xd2, 0xaa, 0xaa, 0xe9, 0x8c, 0x34, 0xad, 0x46, 0x2d, 0xfb, 0xd4, 0xbf, 0xd7, 0xa6, 0xd5,
	0x2f, 0x50, 0xa2, 0xd2, 0x8d, 0x70, 0x23, 0x1e, 0x3a, 0x4e, 0x8c, 0x9c, 0x20, 0x9d, 0xe8, 0xd3,
	0xe8, 0xbc, 0xd2, 0xba, 0x7a, 0x05, 0x5a, 0x51, 0x74, 0x1b, 0x89, 0xaa, 0x06, 0x8b, 0x79, 0x6d,
	0x08, 0x8d, 0x4e, 0x7f, 0x0a, 0xa0, 0x36, 0xb8, 0xf5, 0xc3, 0xab, 0x7f, 0xf9, 0x21, 0xf1, 0xc5,
	0x47, 0xc0, 0x0e, 0x97, 0xe4, 0x2c, 0x83, 0xb7, 0x0e, 0x2c, 0xf2, 0x23, 0x36, 0xc9, 0x8d, 0x0a,
	0x83, 0x38, 0x48, 0x0e, 0xb2, 0xa1, 0xe4, 0x77, 0x6c, 0x4a, 0x50, 0xb8, 0x17, 0x07, 0xc9, 0x6c,
	0x7e, 0x29, 0x76, 0x59, 0x17, 0x2b, 0x57, 0x2d, 0x5c, 0x3b, 0xf3, 0x14, 0xbf, 0x65, 0xb3, 0xb2,
	0x85, 0x1c, 0x61, 0x3d, 0x04, 0x09, 0x27, 0x6e, 0x49, 0x24, 0x28, 0x84, 0x18, 0x43, 0x88, 0xc7,
	0x31, 0x65, 0xc6, 0x48, 0x3e, 0x34, 0xe6, 0x1b, 0x76, 0x42, 0x4b, 0x97, 0x5f, 0x07, 0x5c, 0x41,
	0xdb, 0xab, 0x12, 0xf8, 0x03, 0xdb, 0xf7, 0x4d, 0x9e, 0xec, 0xb6, 0xf4, 0x3d, 0x5e, 0x74, 0xfc,
	0xeb, 0xdf, 0xc5, 0x70, 0xbc, 0xfb, 0xf8, 0xe9, 0xec, 0xef, 0xc3, 0x59, 0xec, 0x0a, 0x2b, 0xfb,
	0xb4, 0x98, 0x3a, 0xe2, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xb0, 0x0f, 0x72, 0xf1, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupProjectionServiceClient is the client API for SignupProjectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupProjectionServiceClient interface {
	Project(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type signupProjectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupProjectionServiceClient(cc *grpc.ClientConn) SignupProjectionServiceClient {
	return &signupProjectionServiceClient{cc}
}

func (c *signupProjectionServiceClient) Project(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/oswee.identity.signup.v1.SignupProjectionService/Project", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupProjectionServiceServer is the server API for SignupProjectionService service.
type SignupProjectionServiceServer interface {
	Project(context.Context, *ProjectRequest) (*empty.Empty, error)
}

// UnimplementedSignupProjectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignupProjectionServiceServer struct {
}

func (*UnimplementedSignupProjectionServiceServer) Project(ctx context.Context, req *ProjectRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Project not implemented")
}

func RegisterSignupProjectionServiceServer(s *grpc.Server, srv SignupProjectionServiceServer) {
	s.RegisterService(&_SignupProjectionService_serviceDesc, srv)
}

func _SignupProjectionService_Project_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupProjectionServiceServer).Project(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.identity.signup.v1.SignupProjectionService/Project",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupProjectionServiceServer).Project(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupProjectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.identity.signup.v1.SignupProjectionService",
	HandlerType: (*SignupProjectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Project",
			Handler:    _SignupProjectionService_Project_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oswee/identity/signup/proto/v1/signup_projection.proto",
}
