// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oswee/identity/signup/proto/v1/signup_event_handler.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Signup               *SignupEntity        `protobuf:"bytes,2,opt,name=signup,proto3" json:"signup,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65784bf58f34f584, []int{0}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *PublishRequest) GetSignup() *SignupEntity {
	if m != nil {
		return m.Signup
	}
	return nil
}

func (m *PublishRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "oswee.identity.signup.v1.PublishRequest")
}

func init() {
	proto.RegisterFile("oswee/identity/signup/proto/v1/signup_event_handler.proto", fileDescriptor_65784bf58f34f584)
}

var fileDescriptor_65784bf58f34f584 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x4b, 0x4b, 0xf4, 0x30,
	0x14, 0xa5, 0xdf, 0xc0, 0x7c, 0x98, 0x01, 0x91, 0x2c, 0xa4, 0x56, 0xd0, 0xe2, 0x42, 0x0a, 0x42,
	0x42, 0xc7, 0x95, 0x08, 0x2e, 0x84, 0x01, 0xc1, 0x8d, 0x74, 0x5c, 0xb9, 0x29, 0xed, 0xcc, 0xb5,
	0x0d, 0xf4, 0x65, 0x73, 0x13, 0x99, 0x5f, 0xe3, 0x5f, 0x95, 0x3c, 0xba, 0xf0, 0x31, 0xe0, 0xee,
	0xe6, 0xde, 0x73, 0x4e, 0xce, 0x39, 0xe4, 0xa6, 0x97, 0xef, 0x00, 0x5c, 0x6c, 0xa1, 0x43, 0x81,
	0x3b, 0x2e, 0x45, 0xd5, 0xa9, 0x81, 0x0f, 0x63, 0x8f, 0x3d, 0xd7, 0xa9, 0x7f, 0xe7, 0xa0, 0xa1,
	0xc3, 0xbc, 0x2e, 0xba, 0x6d, 0x03, 0x23, 0xb3, 0x57, 0x1a, 0x5a, 0x2a, 0x9b, 0xa8, 0xcc, 0x41,
	0x99, 0x4e, 0xa3, 0xf3, 0xaa, 0xef, 0xab, 0x06, 0x9c, 0x4a, 0xa9, 0x5e, 0x39, 0x8a, 0x16, 0x24,
	0x16, 0xed, 0xe0, 0xa8, 0xd1, 0xe9, 0x77, 0x00, 0xb4, 0x03, 0xee, 0xfc, 0xf1, 0xea, 0x4f, 0x96,
	0x1c, 0xf8, 0xe2, 0x23, 0x20, 0x87, 0x4f, 0xaa, 0x6c, 0x84, 0xac, 0x33, 0x78, 0x53, 0x20, 0x91,
	0x1e, 0x91, 0x59, 0x31, 0x88, 0x30, 0x88, 0x83, 0xe4, 0x20, 0x33, 0x23, 0xbd, 0x23, 0x73, 0x47,
	0x0a, 0xff, 0xc5, 0x41, 0xb2, 0x58, 0x5e, 0xb2, 0x7d, 0xd6, 0xd9, 0xda, 0x4e, 0x2b, 0xbb, 0xce,
	0x3c, 0x8b, 0xde, 0x92, 0xc5, 0x66, 0x84, 0x02, 0x21, 0x37, 0x41, 0xc2, 0x99, 0x15, 0x89, 0x98,
	0x0b, 0xc1, 0xa6, 0x10, 0xec, 0x79, 0x4a, 0x99, 0x11, 0x07, 0x37, 0x8b, 0x65, 0x4d, 0x4e, 0xbc,
	0xa8, 0xe9, 0xf0, 0xc1, 0x55, 0xb8, 0x86, 0x51, 0x8b, 0x0d, 0xd0, 0x47, 0xf2, 0xdf, 0xbb, 0xa7,
	0xc9, 0x7e, 0x53, 0x5f, 0x03, 0x46, 0xc7, 0x3f, 0x7e, 0x5e, 0x99, 0xfa, 0xee, 0xe3, 0x97, 0xb3,
	0xdf, 0xab, 0x93, 0xa8, 0x4a, 0xc9, 0x75, 0x5a, 0xce, 0x2d, 0xe3, 0xfa, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x6b, 0xde, 0x3e, 0xab, 0xf6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupEventHandlerServiceClient is the client API for SignupEventHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupEventHandlerServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type signupEventHandlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupEventHandlerServiceClient(cc *grpc.ClientConn) SignupEventHandlerServiceClient {
	return &signupEventHandlerServiceClient{cc}
}

func (c *signupEventHandlerServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/oswee.identity.signup.v1.SignupEventHandlerService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupEventHandlerServiceServer is the server API for SignupEventHandlerService service.
type SignupEventHandlerServiceServer interface {
	Publish(context.Context, *PublishRequest) (*empty.Empty, error)
}

// UnimplementedSignupEventHandlerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignupEventHandlerServiceServer struct {
}

func (*UnimplementedSignupEventHandlerServiceServer) Publish(ctx context.Context, req *PublishRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterSignupEventHandlerServiceServer(s *grpc.Server, srv SignupEventHandlerServiceServer) {
	s.RegisterService(&_SignupEventHandlerService_serviceDesc, srv)
}

func _SignupEventHandlerService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupEventHandlerServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.identity.signup.v1.SignupEventHandlerService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupEventHandlerServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupEventHandlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.identity.signup.v1.SignupEventHandlerService",
	HandlerType: (*SignupEventHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _SignupEventHandlerService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oswee/identity/signup/proto/v1/signup_event_handler.proto",
}
